"""empty message

Revision ID: aa33daf8f3eb
Revises: f6df9995d5f9
Create Date: 2022-10-16 15:22:32.437171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa33daf8f3eb'
down_revision = 'f6df9995d5f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emprestimo_livro',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('livro_id', sa.Integer(), nullable=True),
    sa.Column('aluno_id', sa.Integer(), nullable=True),
    sa.Column('data_emprestimo', sa.Date(), nullable=True),
    sa.Column('data_devolucao', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['aluno_id'], ['aluno.id'], ),
    sa.ForeignKeyConstraint(['livro_id'], ['livro.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('aluno', 'foto')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aluno', sa.Column('foto', sa.VARCHAR(), nullable=True))
    op.drop_table('emprestimo_livro')
    # ### end Alembic commands ###
