"""empty message

Revision ID: f6df9995d5f9
Revises: 
Create Date: 2022-10-16 11:52:20.078748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6df9995d5f9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aluno',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('sobrenome', sa.String(), nullable=True),
    sa.Column('genero', sa.String(), nullable=True),
    sa.Column('escola', sa.String(), nullable=True),
    sa.Column('ano', sa.String(), nullable=True),
    sa.Column('rua', sa.String(), nullable=True),
    sa.Column('numero', sa.String(), nullable=True),
    sa.Column('bairro', sa.String(), nullable=True),
    sa.Column('cidade', sa.String(), nullable=True),
    sa.Column('estado', sa.String(), nullable=True),
    sa.Column('fone', sa.String(), nullable=True),
    sa.Column('cpf', sa.String(), nullable=True),
    sa.Column('foto', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('livro',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('codigo', sa.String(), nullable=True),
    sa.Column('sub_codigo', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('oficina',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('inicio', sa.Date(), nullable=True),
    sa.Column('fim', sa.Date(), nullable=True),
    sa.Column('dia_semana', sa.String(), nullable=True),
    sa.Column('horario', sa.Time(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('login', sa.String(length=100), nullable=True),
    sa.Column('senha', sa.String(length=100), nullable=True),
    sa.Column('nome', sa.String(length=1000), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login')
    )
    op.create_table('aula',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('oficina_id', sa.Integer(), nullable=True),
    sa.Column('data', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['oficina_id'], ['oficina.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matricula',
    sa.Column('aluno', sa.Integer(), nullable=False),
    sa.Column('oficina', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['aluno'], ['aluno.id'], ),
    sa.ForeignKeyConstraint(['oficina'], ['oficina.id'], ),
    sa.PrimaryKeyConstraint('aluno', 'oficina')
    )
    op.create_table('frequencia',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('aula_id', sa.Integer(), nullable=True),
    sa.Column('aluno_id', sa.Integer(), nullable=True),
    sa.Column('presenca', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['aluno_id'], ['aluno.id'], ),
    sa.ForeignKeyConstraint(['aula_id'], ['aula.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('frequencia')
    op.drop_table('matricula')
    op.drop_table('aula')
    op.drop_table('usuario')
    op.drop_table('oficina')
    op.drop_table('livro')
    op.drop_table('aluno')
    # ### end Alembic commands ###
